/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package des.aes;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sun.misc.BASE64Encoder;

/**
 *
 * @author bocal
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cifrado DES&AES");

        jLabel2.setText("Elija por que método quiere cifrar");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Cifrado DES");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cifrado AES");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel6.setText("Ingresa una clave de 8 caracteres");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel7.setText(" Ingresa una clave de 16,24 o 32 caracteres");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 51, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cifrar DES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Descifrar DES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cifrar AES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Descifrar AES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/des/aes/telefono4.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/des/aes/telefono4.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel7))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3)
                .addGap(331, 331, 331)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel7))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jButton3))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jButton4))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String clave2=jTextField1.getText();
        if(clave2.length()!=8){
            JOptionPane.showMessageDialog(rootPane, "Deben de ser de 8 caracteres >:c");
        }else{
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo=fc.getSelectedFile();
        
            String textoT="";
            try{
                FileReader fr = new FileReader(archivo);
                BufferedReader br = new BufferedReader(fr);
                SecretKeyFactory skf = SecretKeyFactory.getInstance("DES");
                DESKeySpec kspec = new DESKeySpec(clave2.getBytes());
                //KeyGenerator generadorDES = KeyGenerator.getInstance("DES");
                //generadorDES.init(56);
                SecretKey clave= skf.generateSecret(kspec);
                //mostrarBytes(clave.getEncoded());
                textoT=textoT+" xd La codificacion es: "+clave.getEncoded()+"\n";
                Cipher cifrado=Cipher.getInstance("DES/ECB/PKCS5Padding");
                String nuearchivo="";
                for (int i = 0; i < archivo.getAbsolutePath().length()-4; i++) {
                    nuearchivo=nuearchivo+archivo.getAbsolutePath().charAt(i);
                }
                textoT=textoT+"el archivito esta en: "+nuearchivo+"cifradodes.txt"+"\n";
                cifrado.init(Cipher.ENCRYPT_MODE,clave);

                byte[] buffer = new byte[1000];
                byte[] buffercifrado;

                FileInputStream in= new FileInputStream(archivo);
                FileOutputStream out = new FileOutputStream(nuearchivo+"cifradodes.txt");

                int bytesleidos = in.read(buffer, 0, 1000);
                while(bytesleidos !=-1){
                    buffercifrado = cifrado.update(buffer,0,bytesleidos);
                    out.write(buffercifrado);
                    bytesleidos = in.read(buffer,0,1000);
                }
                buffercifrado=cifrado.doFinal();
                out.write(buffercifrado);

                in.close();
                out.close();

                jTextArea1.setText(textoT);
            }catch(Exception e){
                System.out.println("Nel no se puede xd "+e);
                JOptionPane.showMessageDialog(rootPane, "Ingresa un archivo tipo TXT >:V");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String clave2=jTextField1.getText();
        String textoT="";
        if(clave2.length()!=8){
            JOptionPane.showMessageDialog(rootPane, "Deben de ser de 8 caracteres >:c");
        }else{
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo=fc.getSelectedFile();
        
            try{
                FileReader fr = new FileReader(archivo);
                BufferedReader br = new BufferedReader(fr);
                SecretKeyFactory skf = SecretKeyFactory.getInstance("DES");
                DESKeySpec kspec = new DESKeySpec(clave2.getBytes());
                //KeyGenerator generadorDES = KeyGenerator.getInstance("DES");
                //generadorDES.init(56);
                SecretKey clave= skf.generateSecret(kspec);
                //mostrarBytes(clave.getEncoded());
                String nuearchivo="";
                for (int i = 0; i < archivo.getAbsolutePath().length()-4; i++) {
                    nuearchivo=nuearchivo+archivo.getAbsolutePath().charAt(i);
                }
                textoT=textoT+"La clave con la codificacion : "+clave.getEncoded()+"\n";
                Cipher cifrado=Cipher.getInstance("DES/ECB/PKCS5Padding");
                textoT=textoT+"El archivo descifrado se encuentra en: "+nuearchivo+"descifradodes.txt"+"\n";

                cifrado.init(Cipher.DECRYPT_MODE,clave);

                byte[] buffer = new byte[1000];
                byte[] buffercifrado;

                byte[] bufferplano;

                FileInputStream in= new FileInputStream(archivo);
                FileOutputStream out = new FileOutputStream(nuearchivo+"descifradodes.txt");

                int bytesleidos = in.read(buffer, 0, 1000);
                while(bytesleidos !=-1){
                    bufferplano = cifrado.update(buffer, 0, bytesleidos);
                    out.write(bufferplano);
                    bytesleidos = in.read(buffer,0,1000);
                }
                bufferplano=cifrado.doFinal();
                out.write(bufferplano);

                in.close();
                out.close();

                jTextArea1.setText(textoT);
            }catch(Exception e){
                System.out.println("No se puede hacr la desifracion"+e);
                JOptionPane.showMessageDialog(rootPane, "Tienes que ingresar un archivo de formato TXT");
            }
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String clave2=jTextField2.getText();
        String textoT="";
        if(clave2.length()!=16 && clave2.length()!=24 && clave2.length()!=32 ){
            JOptionPane.showMessageDialog(rootPane, "Deben ser 16, 24 o 32 caracteres >:u");
        }else{
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo=fc.getSelectedFile();
        
        SecretKeySpec key=new SecretKeySpec(clave2.getBytes(),"AES");
        Cipher cifrado;
        
        try{
            cifrado = Cipher.getInstance("AES");
            cifrado.init(Cipher.ENCRYPT_MODE, key);
            //vamos a generar un bloque de bits para el msj
            String nuearchivo="";
            for (int i = 0; i < archivo.getAbsolutePath().length()-4; i++) {
                nuearchivo=nuearchivo+archivo.getAbsolutePath().charAt(i);
            }
            textoT=textoT+"La clave con la codificacion :  "+key.getEncoded()+"\n";
            textoT=textoT+"2. El archivo cifrado se encuentra en: "+nuearchivo+"cifradoaes.txt"+"\n";
            byte[] buffer = new byte[1000];
            byte[] buffercifrado;
            byte[] bufferplano;

            FileInputStream in= new FileInputStream(archivo);
            FileOutputStream out = new FileOutputStream(nuearchivo+"cifradoaes.txt");

            int bytesleidos = in.read(buffer, 0, 1000);
            while(bytesleidos !=-1){
                buffercifrado = cifrado.update(buffer, 0, bytesleidos);
                
                out.write(buffercifrado);
                bytesleidos = in.read(buffer,0,1000);
            }
            buffercifrado=cifrado.doFinal();
            String base64 = new BASE64Encoder().encode(buffercifrado);
            out.write(buffercifrado);
            
            out.close();
            in.close();
            jTextArea1.setText(textoT);
        }catch(Exception e){
            System.out.println("Nel no se puede xd "+e);
            JOptionPane.showMessageDialog(rootPane, "Ingresa un archivo tipo TXT >:V");
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String clave2=jTextField2.getText();
        String textoT="";
        if(clave2.length()!=16 && clave2.length()!=24 && clave2.length()!=32 ){
            JOptionPane.showMessageDialog(rootPane, "Deben ser 16, 24 o 32 caracteres >:u");
        }else{
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo=fc.getSelectedFile();
        
        SecretKeySpec key=new SecretKeySpec(clave2.getBytes(),"AES");
        Cipher cifrado;
        
        try{
            cifrado = Cipher.getInstance("AES");
            cifrado.init(Cipher.DECRYPT_MODE, key);
            //vamos a generar un bloque de bits para el msj
            String nuearchivo="";
            for (int i = 0; i < archivo.getAbsolutePath().length()-4; i++) {
                nuearchivo=nuearchivo+archivo.getAbsolutePath().charAt(i);
            }
            textoT=textoT+"La codificacion de la clave es:"+key.getEncoded()+"\n";
            textoT=textoT+"El archivo descifrado se encuentra en: "+nuearchivo+"descifradoaes.txt"+"\n";
            byte[] buffer = new byte[1000];
            byte[] buffercifrado;
            byte[] bufferplano;

            FileInputStream in= new FileInputStream(archivo);
            FileOutputStream out = new FileOutputStream(nuearchivo+"descifradoaes.txt");

            int bytesleidos = in.read(buffer, 0, 1000);
            while(bytesleidos !=-1){
                buffercifrado = cifrado.update(buffer, 0, bytesleidos);
                
                out.write(buffercifrado);
                bytesleidos = in.read(buffer,0,1000);
            }
            buffercifrado=cifrado.doFinal();
            String base64 = new BASE64Encoder().encode(buffercifrado);
            out.write(buffercifrado);
            
            out.close();
            in.close();
            jTextArea1.setText(textoT);
        }catch(Exception e){
            System.out.println("Error en descifrar aes"+e);
            JOptionPane.showMessageDialog(rootPane, "Tienes que ingresar un archivo de formato TXT");
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
